### ISSUE TITLE
What features do we need for medicines?

### ISSUE THREAD

**Issue by Imperial-lord** [Imperial-lord/INR-miAyarla#59]
Do we need to have an interface for medicines separately with these features?
1. Medicine Name
2. Time for taking medicines (also maybe a field for before/after meal)
3. Dosage (in case of liquid/number of tablets)

**Comment by Imperial-lord** [comment]
Clicking on a medicine tab would then let the patient access all these details!

**Comment by meceware** [comment]
Yes, that's right. I'm guessing this is for the notification side!

The selection process for the doctor would be
- Medicine Name
- Time + Notes + Dosage (9am - After Breakfast - Half a cup). It would be great if this field can be multiplied. Since the doctors would like to select different times in day. (As take your medicine in 6 hours so 3pm before meal 1 pill, 9pm after meal etc.)
- Repeat time (Every Day/Every week/Every month )

**Comment by meceware** [comment]
Yes, that's right. I'm guessing this is for the notification side! The selection process for the doctor would be

- 1 day full medicine, 1 day half medicine
- Tuesday X medicine, Thursday Y medicine, rest are XXX medicine etc.

so I think, we will need to plan the medicine page weekly. So, the main field will be 

- Medicine Name
- End date (default indefinitely or calendar)

then there could be an accordion or a panel for each day of the week, Monday through Sunday, each day will have

- Time + Notes + Dosage (9am - After Breakfast - Half a cup). It would be great if this field can be multiplied. Since the doctors would like to select different times in day. (As take your medicine in 6 hours so 3pm before meal 1 pill, 9pm after meal etc.)

Any suggestion here is appreciated :)

**Comment by Imperial-lord** [comment]
I am slightly confused at 1 point. So basically, whenever a medicine is due (maybe say 15 mins in advance), the patient should receive a notification? 
Also, there is an additional option to send other notifications, right?

**Comment by Imperial-lord** [comment]
> Yes, that's right. I'm guessing this is for the notification side! The selection process for the doctor would be
> 
> * 1 day full medicine, 1 day half medicine
> * Tuesday X medicine, Thursday Y medicine, rest are XXX medicine etc.
> 
> so I think, we will need to plan the medicine page weekly. So, the main field will be
> 
> * Medicine Name
> * End date (default indefinitely or calendar)
> 
> then there could be an accordion or a panel for each day of the week, Monday through Sunday, each day will have
> 
> * Time + Notes + Dosage (9am - After Breakfast - Half a cup). It would be great if this field can be multiplied. Since the doctors would like to select different times in day. (As take your medicine in 6 hours so 3pm before meal 1 pill, 9pm after meal etc.)
> 
> Any suggestion here is appreciated :)

Let me make a rough wireframe and you can let me know if I understand it fully.

**Comment by meceware** [comment]
I think the only notifications needed would be from the medicine input. I will let you know what's needed here in a couple hours.

**Comment by meceware** [comment]
All right, I talked to my friend, the way I suggested above should be working for them. If you have any questions, I can try to get an answer.

Thank you,
